// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQwMOUr53YSw2CVGpjmDtNYoRl9Sy2afQ',
    appId: '1:891181774950:web:f9cb787b82f3c7168f55a7',
    messagingSenderId: '891181774950',
    projectId: 'mini-project-28bc3',
    authDomain: 'mini-project-28bc3.firebaseapp.com',
    storageBucket: 'mini-project-28bc3.appspot.com',
    measurementId: 'G-B2WSERNP67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUP5hytoYZH15c-nEscO6lvFWgFWypfs0',
    appId: '1:891181774950:android:e95dc1edddb5b3ec8f55a7',
    messagingSenderId: '891181774950',
    projectId: 'mini-project-28bc3',
    storageBucket: 'mini-project-28bc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTBkvTCga6RxFrzHvzsoI0Po0m7JfSjwg',
    appId: '1:891181774950:ios:92202fbeb749ffe38f55a7',
    messagingSenderId: '891181774950',
    projectId: 'mini-project-28bc3',
    storageBucket: 'mini-project-28bc3.appspot.com',
    iosBundleId: 'com.example.miniproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTBkvTCga6RxFrzHvzsoI0Po0m7JfSjwg',
    appId: '1:891181774950:ios:25deb6755356cd8e8f55a7',
    messagingSenderId: '891181774950',
    projectId: 'mini-project-28bc3',
    storageBucket: 'mini-project-28bc3.appspot.com',
    iosBundleId: 'com.example.miniproject.RunnerTests',
  );
}
